# Generated by Django 6.0.3 on 2026-04-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_payment_status_order_transaction_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("razorpay", "Razorpay"),
                    ("card", "Card"),
                    ("upi", "UPI"),
                    ("cod", "Cash on Delivery"),
                ],
                default="cod",
                max_length=20,
            ),
        ),
    ]
