# Generated by Django 6.0.3 on 2026-04-03 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_shipping_fee_order_payment_method_updates"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="checkout_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="INR", max_length=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("created", "Created"), ("paid", "Paid"), ("failed", "Failed")],
                default="created",
                max_length=20,
            ),
        ),
    ]
