# Generated by Django 6.0.3 on 2026-03-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_cart_user_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cart',
        ),
    ]
