# Generated by Django 6.0.3 on 2026-03-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='order',
        ),
    ]
